### ISSUE TITLE
Add integration testing on AKS

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/integration-k8s-aks#1]
### Description
This can be done in few ways:
1. Use cloudtest as in monorepo https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/azure.yaml
2. Use github actions doing steps from https://github.com/networkservicemesh/networkservicemesh/tree/master/.cloudtest/azure.yaml

**Comment by denis-tingaikin** [comment]
secrets are:
```
AZURE_SERVICE_PRINCIPAL
AZURE_SERVICE_PRINCIPAL_SECRET
```
